Repository 89netraM/iMat, pull requests merged in 2019-05, with the labels that each got.

#10 Produkträknare
  src/ProductCounter/ProductCounterComponent.fxml
  src/ProductCounter/ProductCounterComponent.java
Labels: enhancement

#18 Include lib/projectbackend.jar
  .gitignore
  .idea/iMat.iml
  .idea/misc.xml
  .idea/modules.xml
  iMat.iml
  lib/projectbackend.jar
Labels: enhancement

#19 Inclide projectbackend
  .idea/iMat.iml
  .idea/libraries/projectbackend.xml
Labels: bug

#20 Add out/ to .gitignore
  .gitignore
Labels: enhancement

#17 Kvitto
  src/Receipt/ReceiptComponent.fxml
  src/Receipt/ReceiptComponent.java
  src/Receipt/ReceiptItemComponent.fxml
  src/Receipt/ReceiptItemComponent.java
Labels: enhancement

#22 Kategorikarusell
  resources/category_icons/BERRY.png
  resources/category_icons/BREAD.png
  resources/category_icons/CABBAGE.png
  resources/category_icons/CITRUS_FRUIT.png
  resources/category_icons/COLD_DRINKS.png
  resources/category_icons/DAIRIES.png
  resources/category_icons/EXOTIC_FRUIT.png
  resources/category_icons/FISH.png
  resources/category_icons/FLOUR_SUGAR_SALT.png
  resources/category_icons/FRUIT.png
  resources/category_icons/HERB.png
  resources/category_icons/HOT_DRINKS.png
  resources/category_icons/MEAT.png
  resources/category_icons/MELONS.png
  resources/category_icons/NUTS_AND_SEEDS.png
  resources/category_icons/PASTA.png
  resources/category_icons/POD.png
  resources/category_icons/POTATO_RICE.png
  resources/category_icons/ROOT_VEGETABLE.png
  resources/category_icons/SWEET.png
  resources/category_icons/VEGETABLE_FRUIT.png
  src/Animations/DoubleAnimation.java
  src/Animations/IAnimationAction.java
  src/CategoryCarousel/CategoryCarouselComponent.fxml
  src/CategoryCarousel/CategoryCarouselComponent.java
  src/CategoryCarousel/CategoryCarouselItemComponent.fxml
  src/CategoryCarousel/CategoryCarouselItemComponent.java
Labels: enhancement

#25 Uppåt animation
  src/QProducts/QProductListComponent.java
Labels: enhancement

#31 Animerad ingång för kvitto element
  src/Receipt/ReceiptComponent.java
Labels: question

#37 Egna kategorier
  src/CategoryCarousel/Categories.java
  src/CategoryCarousel/CategoryCarouselComponent.java
  src/CategoryCarousel/CategoryCarouselItemComponent.java
Labels: enhancement
